name: "EnigmaFix Release Build"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.).
  BUILD_TYPE: Release
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # We need to update the submodules alongside updating the submodules for Kiero-CMake as an extra precaution.
    - name: Initialize Submodules
      run: git submodule update --init --recursive && cd Source/ThirdParty/Kiero-CMake && git submodule update --init --recursive && cd ../../..
    # Afterwards, we run Nix-Build with our build type, and making sure to allow unsupported systems, for cross-compilation.
    - name: Run Nix-Build
      run: NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build --arg buildType '"${{env.BUILD_TYPE}}"'
    # Before we wrap up, we need to package the binaries into a .ZIP archive, so we can then later upload the artifact, so it can be downloaded.
    - name: Package Windows Binaries
      run: |
        mkdir -p artifacts
        zip -r EnigmaFix-Windows-${{env.BUILD_TYPE}}.zip result/Binaries/Windows/* -x "*.a"
    # Finally, upload the artifact.
    - name: Upload Windows Binaries
      uses: actions/upload-artifact@v4
      with:
        name: Enigmafix-Windows-Build-${{env.BUILD_TYPE}}
        path: Enigmafix-Windows-${{env.BUILD_TYPE}}.zip
