name: "EnigmaFix Release Build"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Initialize Submodules
      run: git submodule update --init --recursive && cd Source/ThirdParty/Kiero-CMake && git submodule update --init --recursive && cd ../../..

    - name: Run Nix-Build
      run: NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build --arg buildType '"${{env.BUILD_TYPE}}"'

    - name: Package Windows Binaries
      run: |
        mkdir -p artifacts
        zip -r EnigmaFix-Windows-${{env.BUILD_TYPE}}.zip result/Binaries/Windows/* -x "*.a"

    - name: Upload Windows Binaries
      uses: actions/upload-artifact@v4
      with:
        name: Enigmafix-Windows-Build-${{env.BUILD_TYPE}}
        path: Enigmafix-Windows-${{env.BUILD_TYPE}}.zip
